/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/teams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a team */
        put: operations["update"];
        post?: never;
        /** Delete a team */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get employee by ID */
        get: operations["getById"];
        /** Update an employee */
        put: operations["update_1"];
        post?: never;
        /** Delete an employee */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a department */
        put: operations["update_2"];
        post?: never;
        /** Delete a department */
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timesheets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all timesheets (Manager/HR filtered by team) */
        get: operations["getAll"];
        put?: never;
        /** Create a timesheet (DRAFT) */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timesheets/{id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add an entry to a timesheet */
        post: operations["addEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all teams, optionally filtered by departmentId */
        get: operations["getAll_1"];
        put?: never;
        /** Create a team under a department */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/salary/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set employee salary (PAYROLL_ADMIN) */
        post: operations["createRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/salary/payslips/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate monthly payslip with PAYE and UIF */
        post: operations["generatePaySlip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/salary/increase-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all salary increase requests (HR/Payroll) */
        get: operations["getAllIncreaseRequests"];
        put?: never;
        /** Submit a salary increase request */
        post: operations["submitIncreaseRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/performance/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a performance review (Manager) */
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/performance/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a goal for an employee (Manager/HR) */
        post: operations["createGoal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/performance/cycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all performance cycles */
        get: operations["getCycles"];
        put?: never;
        /** Create a performance cycle (HR) */
        post: operations["createCycle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all leave requests (HR/Manager filtered) */
        get: operations["getAll_2"];
        put?: never;
        /** Submit a leave request */
        post: operations["submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all employees (paginated, filterable) */
        get: operations["getAll_3"];
        put?: never;
        /** Create a new employee */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload employee profile photo */
        post: operations["uploadPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}/offboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Offboard an employee: terminate, cancel pending leave, deactivate benefits */
        post: operations["offboard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a document */
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all departments */
        get: operations["getAll_4"];
        put?: never;
        /** Create a department */
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/benefits/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply for a benefit */
        post: operations["apply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset a password using a valid reset token */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a refresh token for a new access + refresh token pair */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a refresh token (logout) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and receive a JWT token */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a password reset token for an email */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change own password */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timesheets/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Submit a timesheet for approval */
        patch: operations["submit_1"];
        trace?: never;
    };
    "/timesheets/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reject a timesheet */
        patch: operations["reject"];
        trace?: never;
    };
    "/timesheets/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Approve a timesheet */
        patch: operations["approve"];
        trace?: never;
    };
    "/salary/increase-requests/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reject a salary increase request (HR_ADMIN) */
        patch: operations["rejectIncreaseRequest"];
        trace?: never;
    };
    "/salary/increase-requests/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Approve a salary increase request (HR_ADMIN) */
        patch: operations["approveIncreaseRequest"];
        trace?: never;
    };
    "/performance/reviews/{id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Acknowledge a performance review (Employee) */
        patch: operations["acknowledge"];
        trace?: never;
    };
    "/performance/goals/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update goal status */
        patch: operations["updateGoalStatus"];
        trace?: never;
    };
    "/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark a notification as read */
        patch: operations["markAsRead"];
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark all notifications as read */
        patch: operations["markAllAsRead"];
        trace?: never;
    };
    "/leave/requests/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reject a leave request */
        patch: operations["reject_1"];
        trace?: never;
    };
    "/leave/requests/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Approve a leave request */
        patch: operations["approve_1"];
        trace?: never;
    };
    "/employees/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update employee employment status */
        patch: operations["updateStatus"];
        trace?: never;
    };
    "/documents/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Verify a document (HR only) */
        patch: operations["verify"];
        trace?: never;
    };
    "/documents/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reject a document (HR only) */
        patch: operations["reject_2"];
        trace?: never;
    };
    "/benefits/applications/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reject a benefit application (HR) */
        patch: operations["reject_3"];
        trace?: never;
    };
    "/benefits/applications/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Approve a benefit application (HR) */
        patch: operations["approve_2"];
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated employee profile */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update own profile (name, phone, address, nationality, gender) */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/timesheets/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current employee's timesheets */
        get: operations["getMy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/salary/records/{employeeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get salary history for an employee */
        get: operations["getSalaryHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/salary/payslips/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single payslip */
        get: operations["getPaySlip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/salary/payslips/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current employee's payslips */
        get: operations["getMyPaySlips"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/salary/increase-requests/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current employee's salary increase requests */
        get: operations["getMyIncreaseRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/performance/reviews/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current employee's reviews */
        get: operations["getMyReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/performance/goals/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current employee's goals */
        get: operations["getMyGoals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current employee's notifications */
        get: operations["getMy_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/requests/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current employee's leave requests */
        get: operations["getMy_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get approved leaves for a given month (team calendar) */
        get: operations["getCalendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/balances/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current employee's leave balances */
        get: operations["getMyBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/photo/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve employee profile photo */
        get: operations["getPhoto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all documents (HR_ADMIN only) */
        get: operations["getAll_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a document */
        get: operations["download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current employee's documents */
        get: operations["getMy_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard stats (HR/Admin) */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/benefits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all available benefit types */
        get: operations["getAllTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/benefits/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current employee's active benefits */
        get: operations["getMy_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get audit logs (HR_ADMIN/SUPER_ADMIN), filterable by entity type, employee, date range */
        get: operations["getAll_6"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timesheets/{id}/entries/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an entry from a DRAFT timesheet */
        delete: operations["deleteEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel a leave request (employee only, must be PENDING) */
        delete: operations["cancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Department: {
            /** Format: int64 */
            id?: number;
            name?: string;
            description?: string;
        };
        Team: {
            /** Format: int64 */
            id?: number;
            name?: string;
            description?: string;
            department?: components["schemas"]["Department"];
        };
        ApiResponseTeam: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["Team"];
        };
        EmployeeRequest: {
            firstName?: string;
            lastName?: string;
            email?: string;
            phone?: string;
            /** Format: date */
            dateOfBirth?: string;
            gender?: string;
            nationality?: string;
            idNumber?: string;
            address?: string;
            jobTitle?: string;
            password?: string;
            /** @enum {string} */
            employmentType?: "FULL_TIME" | "PART_TIME";
            /** @enum {string} */
            employmentStatus?: "ACTIVE" | "INACTIVE" | "SUSPENDED" | "TERMINATED";
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** Format: int64 */
            departmentId?: number;
            /** Format: int64 */
            teamId?: number;
            managerId?: string;
            /** @enum {string} */
            role?: "EMPLOYEE" | "MANAGER" | "HR_ADMIN" | "PAYROLL_ADMIN" | "SUPER_ADMIN";
        };
        ApiResponseEmployeeResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["EmployeeResponse"];
        };
        EmployeeResponse: {
            id?: string;
            employeeNumber?: string;
            firstName?: string;
            lastName?: string;
            email?: string;
            phone?: string;
            dateOfBirth?: string;
            gender?: string;
            nationality?: string;
            address?: string;
            jobTitle?: string;
            /** @enum {string} */
            role?: "EMPLOYEE" | "MANAGER" | "HR_ADMIN" | "PAYROLL_ADMIN" | "SUPER_ADMIN";
            /** @enum {string} */
            employmentStatus?: "ACTIVE" | "INACTIVE" | "SUSPENDED" | "TERMINATED";
            /** @enum {string} */
            employmentType?: "FULL_TIME" | "PART_TIME";
            profilePhoto?: string;
            startDate?: string;
            endDate?: string;
            /** Format: int64 */
            departmentId?: number;
            department?: string;
            /** Format: int64 */
            teamId?: number;
            team?: string;
            managerId?: string;
            manager?: string;
        };
        ApiResponseDepartment: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["Department"];
        };
        TimesheetRequest: {
            /** Format: date */
            weekStartDate?: string;
            /** Format: date */
            weekEndDate?: string;
        };
        ApiResponseTimesheetResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TimesheetResponse"];
        };
        EmployeeSummary: {
            id?: string;
            firstName?: string;
            lastName?: string;
            employeeNumber?: string;
        };
        TimesheetEntryResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: date */
            date?: string;
            hoursWorked?: number;
            description?: string;
            projectOrTask?: string;
        };
        TimesheetResponse: {
            id?: string;
            employee?: components["schemas"]["EmployeeSummary"];
            /** Format: date */
            weekStartDate?: string;
            /** Format: date */
            weekEndDate?: string;
            totalHours?: number;
            /** @enum {string} */
            status?: "DRAFT" | "SUBMITTED" | "APPROVED" | "REJECTED";
            approvedBy?: components["schemas"]["EmployeeSummary"];
            /** Format: date-time */
            approvedAt?: string;
            rejectionReason?: string;
            /** Format: date-time */
            createdAt?: string;
            entries?: components["schemas"]["TimesheetEntryResponse"][];
        };
        TimesheetEntryRequest: {
            /** Format: date */
            date?: string;
            hoursWorked?: number;
            description?: string;
            projectOrTask?: string;
        };
        SalaryRecordRequest: {
            employeeId?: string;
            basicSalary?: number;
            /** Format: date */
            effectiveDate?: string;
        };
        ApiResponseSalaryRecordResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["SalaryRecordResponse"];
        };
        SalaryRecordResponse: {
            id?: string;
            employee?: components["schemas"]["EmployeeSummary"];
            basicSalary?: number;
            /** Format: date */
            effectiveDate?: string;
            /** Format: date */
            endDate?: string;
            createdBy?: components["schemas"]["EmployeeSummary"];
            /** Format: date-time */
            createdAt?: string;
        };
        PaySlipGenerateRequest: {
            employeeId?: string;
            month?: string;
            medicalAid?: number;
            pensionFund?: number;
            otherDeductions?: number;
        };
        ApiResponsePaySlipResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PaySlipResponse"];
        };
        PaySlipResponse: {
            id?: string;
            employee?: components["schemas"]["EmployeeSummary"];
            month?: string;
            basicSalary?: number;
            grossSalary?: number;
            uif?: number;
            paye?: number;
            medicalAid?: number;
            pensionFund?: number;
            otherDeductions?: number;
            netSalary?: number;
            /** Format: int32 */
            taxYear?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        SalaryIncreaseRequestDto: {
            employeeId?: string;
            justification?: string;
            proposedSalary?: number;
        };
        ApiResponseSalaryIncreaseRequestResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["SalaryIncreaseRequestResponse"];
        };
        SalaryIncreaseRequestResponse: {
            id?: string;
            employeeId?: string;
            employeeName?: string;
            requestedById?: string;
            requestedByName?: string;
            currentSalary?: number;
            proposedSalary?: number;
            increasePercentage?: number;
            justification?: string;
            /** @enum {string} */
            status?: "PENDING" | "APPROVED" | "REJECTED";
            reviewedById?: string;
            reviewedByName?: string;
            /** Format: date-time */
            reviewedAt?: string;
            rejectionReason?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        PerformanceReviewRequest: {
            employeeId?: string;
            cycleId?: string;
            /** Format: int32 */
            overallRating?: number;
            strengths?: string;
            areasForImprovement?: string;
            comments?: string;
        };
        ApiResponsePerformanceReviewResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PerformanceReviewResponse"];
        };
        PerformanceReviewResponse: {
            id?: string;
            employeeId?: string;
            employeeName?: string;
            reviewerId?: string;
            reviewerName?: string;
            cycleId?: string;
            cycleName?: string;
            /** Format: int32 */
            overallRating?: number;
            strengths?: string;
            areasForImprovement?: string;
            comments?: string;
            /** @enum {string} */
            status?: "DRAFT" | "SUBMITTED" | "ACKNOWLEDGED";
            /** Format: date-time */
            acknowledgedAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        PerformanceGoalRequest: {
            employeeId?: string;
            cycleId?: string;
            title?: string;
            description?: string;
            /** Format: date */
            targetDate?: string;
        };
        ApiResponsePerformanceGoalResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PerformanceGoalResponse"];
        };
        PerformanceGoalResponse: {
            id?: string;
            employeeId?: string;
            employeeName?: string;
            cycleId?: string;
            cycleName?: string;
            title?: string;
            description?: string;
            /** Format: date */
            targetDate?: string;
            /** @enum {string} */
            status?: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
            /** Format: int32 */
            rating?: number;
            createdById?: string;
            createdByName?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        PerformanceCycleRequest: {
            name?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
        };
        ApiResponsePerformanceCycle: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PerformanceCycle"];
        };
        PerformanceCycle: {
            id?: string;
            name?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "CLOSED";
        };
        LeaveRequestDto: {
            /** Format: int64 */
            leaveTypeId: number;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            reason?: string;
            documentationConfirmed?: boolean;
        };
        ApiResponseLeaveRequestResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["LeaveRequestResponse"];
        };
        LeaveRequestResponse: {
            id?: string;
            employee?: components["schemas"]["EmployeeSummary"];
            leaveType?: components["schemas"]["LeaveTypeSummary"];
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            totalDays?: number;
            reason?: string;
            /** @enum {string} */
            status?: "PENDING" | "APPROVED" | "REJECTED" | "CANCELLED";
            approvedBy?: components["schemas"]["EmployeeSummary"];
            /** Format: date-time */
            approvedAt?: string;
            rejectionReason?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        LeaveTypeSummary: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** Format: int32 */
            defaultDays?: number;
            requiresDocumentation?: boolean;
            isPaid?: boolean;
        };
        OffboardEmployeeRequest: {
            reason: string;
            /** Format: date */
            lastWorkingDay?: string;
        };
        ApiResponseDocumentResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["DocumentResponse"];
        };
        DocumentResponse: {
            id?: string;
            employee?: components["schemas"]["EmployeeSummary"];
            /** @enum {string} */
            documentType?: "ID" | "CONTRACT" | "CERTIFICATE" | "PAYSLIP" | "OTHER";
            fileName?: string;
            fileSize?: number;
            uploadedBy?: components["schemas"]["EmployeeSummary"];
            verifiedBy?: components["schemas"]["EmployeeSummary"];
            /** Format: date-time */
            verifiedAt?: string;
            /** @enum {string} */
            status?: "PENDING" | "VERIFIED" | "REJECTED";
            /** Format: date-time */
            createdAt?: string;
        };
        ApiResponseBenefitApplicationResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["BenefitApplicationResponse"];
        };
        BenefitApplicationResponse: {
            id?: string;
            employeeId?: string;
            employeeName?: string;
            /** Format: int64 */
            benefitTypeId?: number;
            benefitTypeName?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "PENDING" | "APPROVED" | "REJECTED";
            reviewedById?: string;
            reviewedByName?: string;
            /** Format: date-time */
            reviewedAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ResetPasswordRequest: {
            token: string;
            newPassword: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            message?: string;
            data?: unknown;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        ApiResponseMapStringObject: {
            success?: boolean;
            message?: string;
            data?: {
                [key: string]: unknown;
            };
        };
        ForgotPasswordRequest: {
            email: string;
        };
        ApiResponseMapStringString: {
            success?: boolean;
            message?: string;
            data?: {
                [key: string]: string;
            };
        };
        ChangePasswordRequest: {
            currentPassword?: string;
            newPassword?: string;
        };
        ApiResponseNotificationResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["NotificationResponse"];
        };
        NotificationResponse: {
            id?: string;
            recipientId?: string;
            title?: string;
            message?: string;
            /** @enum {string} */
            type?: "LEAVE" | "TIMESHEET" | "SALARY" | "DOCUMENT" | "GENERAL" | "OFFBOARDING";
            isRead?: boolean;
            relatedEntityType?: string;
            relatedEntityId?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        UpdateMeRequest: {
            firstName?: string;
            lastName?: string;
            phone?: string;
            address?: string;
            nationality?: string;
            gender?: string;
        };
        ApiResponseMeResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["MeResponse"];
        };
        MeResponse: {
            id?: string;
            employeeNumber?: string;
            firstName?: string;
            lastName?: string;
            email?: string;
            phone?: string;
            jobTitle?: string;
            address?: string;
            nationality?: string;
            gender?: string;
            /** @enum {string} */
            role?: "EMPLOYEE" | "MANAGER" | "HR_ADMIN" | "PAYROLL_ADMIN" | "SUPER_ADMIN";
            /** @enum {string} */
            employmentStatus?: "ACTIVE" | "INACTIVE" | "SUSPENDED" | "TERMINATED";
            /** @enum {string} */
            employmentType?: "FULL_TIME" | "PART_TIME";
            profilePhoto?: string;
            /** Format: int64 */
            departmentId?: number;
            department?: string;
            /** Format: int64 */
            teamId?: number;
            team?: string;
            startDate?: string;
        };
        ApiResponseListTimesheetResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TimesheetResponse"][];
        };
        ApiResponseListTeam: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["Team"][];
        };
        ApiResponseListSalaryRecordResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["SalaryRecordResponse"][];
        };
        ApiResponseListPaySlipResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PaySlipResponse"][];
        };
        ApiResponseListSalaryIncreaseRequestResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["SalaryIncreaseRequestResponse"][];
        };
        ApiResponseListPerformanceReviewResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PerformanceReviewResponse"][];
        };
        ApiResponseListPerformanceGoalResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PerformanceGoalResponse"][];
        };
        ApiResponseListPerformanceCycle: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PerformanceCycle"][];
        };
        ApiResponseListNotificationResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["NotificationResponse"][];
        };
        ApiResponseListLeaveRequestResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["LeaveRequestResponse"][];
        };
        ApiResponseListLeaveBalanceResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["LeaveBalanceResponse"][];
        };
        LeaveBalanceResponse: {
            /** Format: int64 */
            id?: number;
            employee?: components["schemas"]["EmployeeSummary"];
            leaveType?: components["schemas"]["LeaveTypeSummary"];
            totalDays?: number;
            usedDays?: number;
            remainingDays?: number;
            /** Format: date */
            cycleStartDate?: string;
            /** Format: date */
            cycleEndDate?: string;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        ApiResponsePageEmployeeResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageObject"];
        };
        PageObject: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["EmployeeResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            unpaged?: boolean;
            paged?: boolean;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNumber?: number;
        };
        SortObject: {
            empty?: boolean;
            unsorted?: boolean;
            sorted?: boolean;
        };
        ApiResponseListDocumentResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["DocumentResponse"][];
        };
        ApiResponseListDepartment: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["Department"][];
        };
        ApiResponseListBenefitType: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["BenefitType"][];
        };
        BenefitType: {
            /** Format: int64 */
            id?: number;
            name?: string;
            description?: string;
            employeeContribution?: number;
            employerContribution?: number;
            isOptional?: boolean;
        };
        ApiResponseListEmployeeBenefitResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["EmployeeBenefitResponse"][];
        };
        EmployeeBenefitResponse: {
            id?: string;
            employeeId?: string;
            employeeName?: string;
            /** Format: int64 */
            benefitTypeId?: number;
            benefitTypeName?: string;
            employeeContribution?: number;
            employerContribution?: number;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "PENDING" | "APPROVED" | "REJECTED";
        };
        ApiResponsePageAuditLogResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageObject"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Team"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTeam"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmployeeResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmployeeResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Department"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDepartment"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTimesheetResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimesheetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTimesheetResponse"];
                };
            };
        };
    };
    addEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimesheetEntryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTimesheetResponse"];
                };
            };
        };
    };
    getAll_1: {
        parameters: {
            query?: {
                departmentId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTeam"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query: {
                departmentId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Team"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTeam"];
                };
            };
        };
    };
    createRecord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalaryRecordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSalaryRecordResponse"];
                };
            };
        };
    };
    generatePaySlip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaySlipGenerateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePaySlipResponse"];
                };
            };
        };
    };
    getAllIncreaseRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListSalaryIncreaseRequestResponse"];
                };
            };
        };
    };
    submitIncreaseRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalaryIncreaseRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSalaryIncreaseRequestResponse"];
                };
            };
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PerformanceReviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePerformanceReviewResponse"];
                };
            };
        };
    };
    createGoal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PerformanceGoalRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePerformanceGoalResponse"];
                };
            };
        };
    };
    getCycles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPerformanceCycle"];
                };
            };
        };
    };
    createCycle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PerformanceCycleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePerformanceCycle"];
                };
            };
        };
    };
    getAll_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListLeaveRequestResponse"];
                };
            };
        };
    };
    submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaveRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLeaveRequestResponse"];
                };
            };
        };
    };
    getAll_3: {
        parameters: {
            query: {
                departmentId?: number;
                teamId?: number;
                status?: "ACTIVE" | "INACTIVE" | "SUSPENDED" | "TERMINATED";
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageEmployeeResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmployeeResponse"];
                };
            };
        };
    };
    uploadPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmployeeResponse"];
                };
            };
        };
    };
    offboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OffboardEmployeeRequest"];
            };
        };
        responses: {
            /** @description Employee is already terminated */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmployeeResponse"];
                };
            };
        };
    };
    upload: {
        parameters: {
            query: {
                type: "ID" | "CONTRACT" | "CERTIFICATE" | "PAYSLIP" | "OTHER";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDocumentResponse"];
                };
            };
        };
    };
    getAll_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListDepartment"];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Department"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDepartment"];
                };
            };
        };
    };
    apply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: number;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBenefitApplicationResponse"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMapStringObject"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMapStringObject"];
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMapStringString"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    submit_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTimesheetResponse"];
                };
            };
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTimesheetResponse"];
                };
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTimesheetResponse"];
                };
            };
        };
    };
    rejectIncreaseRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSalaryIncreaseRequestResponse"];
                };
            };
        };
    };
    approveIncreaseRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSalaryIncreaseRequestResponse"];
                };
            };
        };
    };
    acknowledge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePerformanceReviewResponse"];
                };
            };
        };
    };
    updateGoalStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePerformanceGoalResponse"];
                };
            };
        };
    };
    markAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseNotificationResponse"];
                };
            };
        };
    };
    markAllAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    reject_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLeaveRequestResponse"];
                };
            };
        };
    };
    approve_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLeaveRequestResponse"];
                };
            };
        };
    };
    updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmployeeResponse"];
                };
            };
        };
    };
    verify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDocumentResponse"];
                };
            };
        };
    };
    reject_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDocumentResponse"];
                };
            };
        };
    };
    reject_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBenefitApplicationResponse"];
                };
            };
        };
    };
    approve_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBenefitApplicationResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMeResponse"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMeResponse"];
                };
            };
        };
    };
    getMy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTimesheetResponse"];
                };
            };
        };
    };
    getSalaryHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employeeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListSalaryRecordResponse"];
                };
            };
        };
    };
    getPaySlip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePaySlipResponse"];
                };
            };
        };
    };
    getMyPaySlips: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPaySlipResponse"];
                };
            };
        };
    };
    getMyIncreaseRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListSalaryIncreaseRequestResponse"];
                };
            };
        };
    };
    getMyReviews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPerformanceReviewResponse"];
                };
            };
        };
    };
    getMyGoals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPerformanceGoalResponse"];
                };
            };
        };
    };
    getMy_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListNotificationResponse"];
                };
            };
        };
    };
    getMy_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListLeaveRequestResponse"];
                };
            };
        };
    };
    getCalendar: {
        parameters: {
            query: {
                year: number;
                month: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListLeaveRequestResponse"];
                };
            };
        };
    };
    getMyBalances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListLeaveBalanceResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getAll_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListDocumentResponse"];
                };
            };
        };
    };
    download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getMy_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListDocumentResponse"];
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMapStringObject"];
                };
            };
        };
    };
    getAllTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListBenefitType"];
                };
            };
        };
    };
    getMy_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListEmployeeBenefitResponse"];
                };
            };
        };
    };
    getAll_6: {
        parameters: {
            query: {
                entityType?: string;
                employeeId?: string;
                from?: string;
                to?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageAuditLogResponse"];
                };
            };
        };
    };
    deleteEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                entryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTimesheetResponse"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
}
