-- V1 baseline schema for EmployeeHub.
--
-- This migration reproduces exactly the schema Hibernate generated from the JPA
-- entities under ddl-auto=update (captured via pg_dump --schema-only). From here
-- on Flyway owns the schema and Hibernate runs with ddl-auto=validate, so this
-- file and the entities must stay in lock-step: any entity change ships with a
-- new V{n} migration in the same commit.
--
-- Constraint names (fk*, uk*) match Hibernate's generated names so validate and
-- future diffs line up with what the ORM expects.

-- ─────────────────────────────────────────────────────────────────────────────
-- Reference / lookup tables (Long identity ids)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE departments (
    id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description character varying(255),
    name        character varying(255) NOT NULL
);

CREATE TABLE teams (
    id            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description   character varying(255),
    name          character varying(255) NOT NULL,
    department_id bigint NOT NULL
);

CREATE TABLE leave_types (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cycle_years            integer NOT NULL,
    default_days           integer NOT NULL,
    is_paid                boolean NOT NULL,
    name                   character varying(255) NOT NULL,
    requires_documentation boolean NOT NULL
);

CREATE TABLE benefit_types (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description           character varying(255),
    employee_contribution numeric(38,2) NOT NULL,
    employer_contribution numeric(38,2) NOT NULL,
    is_optional           boolean NOT NULL,
    name                  character varying(255) NOT NULL
);

CREATE TABLE tax_brackets (
    id            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    base_tax      numeric(38,2) NOT NULL,
    marginal_rate numeric(38,2) NOT NULL,
    max_income    numeric(38,2),
    min_income    numeric(38,2) NOT NULL,
    rebate        numeric(38,2) NOT NULL,
    tax_year      integer NOT NULL
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Core entities (String/UUID ids)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE employees (
    id                    character varying(255) NOT NULL,
    address               character varying(255),
    created_at            timestamp(6) without time zone,
    date_of_birth         date,
    email                 character varying(255) NOT NULL,
    employee_number       character varying(255) NOT NULL,
    employment_status     character varying(255) NOT NULL,
    employment_type       character varying(255) NOT NULL,
    end_date              date,
    failed_login_attempts integer DEFAULT 0 NOT NULL,
    first_name            character varying(255) NOT NULL,
    gender                character varying(255),
    id_number             character varying(255),
    job_title             character varying(255) NOT NULL,
    last_name             character varying(255) NOT NULL,
    locked_until          timestamp(6) without time zone,
    nationality           character varying(255),
    password              character varying(255),
    phone                 character varying(255),
    profile_photo         character varying(255),
    role                  character varying(255) NOT NULL,
    start_date            date NOT NULL,
    updated_at            timestamp(6) without time zone,
    department_id         bigint NOT NULL,
    manager_id            character varying(255),
    team_id               bigint NOT NULL,
    CONSTRAINT employees_employment_status_check CHECK (((employment_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'SUSPENDED'::character varying, 'TERMINATED'::character varying])::text[]))),
    CONSTRAINT employees_employment_type_check CHECK (((employment_type)::text = ANY ((ARRAY['FULL_TIME'::character varying, 'PART_TIME'::character varying])::text[]))),
    CONSTRAINT employees_role_check CHECK (((role)::text = ANY ((ARRAY['EMPLOYEE'::character varying, 'MANAGER'::character varying, 'HR_ADMIN'::character varying, 'PAYROLL_ADMIN'::character varying, 'SUPER_ADMIN'::character varying])::text[])))
);

CREATE TABLE leave_balances (
    id               bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cycle_end_date   date NOT NULL,
    cycle_start_date date NOT NULL,
    remaining_days   numeric(38,2) NOT NULL,
    total_days       numeric(38,2) NOT NULL,
    used_days        numeric(38,2) NOT NULL,
    employee_id      character varying(255) NOT NULL,
    leave_type_id    bigint NOT NULL
);

CREATE TABLE leave_requests (
    id               character varying(255) NOT NULL,
    approved_at      timestamp(6) without time zone,
    created_at       timestamp(6) without time zone,
    end_date         date NOT NULL,
    reason           character varying(255),
    rejection_reason character varying(255),
    start_date       date NOT NULL,
    status           character varying(255) NOT NULL,
    total_days       numeric(38,2) NOT NULL,
    approved_by_id   character varying(255),
    employee_id      character varying(255) NOT NULL,
    leave_type_id    bigint NOT NULL,
    CONSTRAINT leave_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying])::text[])))
);

CREATE TABLE timesheets (
    id               character varying(255) NOT NULL,
    approved_at      timestamp(6) without time zone,
    created_at       timestamp(6) without time zone,
    rejection_reason character varying(255),
    status           character varying(255) NOT NULL,
    total_hours      numeric(38,2) NOT NULL,
    week_end_date    date NOT NULL,
    week_start_date  date NOT NULL,
    approved_by_id   character varying(255),
    employee_id      character varying(255) NOT NULL,
    CONSTRAINT timesheets_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'SUBMITTED'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);

CREATE TABLE timesheet_entries (
    id              bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date            date NOT NULL,
    description     character varying(255),
    hours_worked    numeric(38,2) NOT NULL,
    project_or_task character varying(255),
    timesheet_id    character varying(255) NOT NULL
);

CREATE TABLE documents (
    id             character varying(255) NOT NULL,
    created_at     timestamp(6) without time zone,
    document_type  character varying(255) NOT NULL,
    file_name      character varying(255) NOT NULL,
    file_size      numeric(38,2),
    file_url       character varying(255) NOT NULL,
    status         character varying(255) NOT NULL,
    verified_at    timestamp(6) without time zone,
    employee_id    character varying(255) NOT NULL,
    uploaded_by_id character varying(255) NOT NULL,
    verified_by_id character varying(255),
    CONSTRAINT documents_document_type_check CHECK (((document_type)::text = ANY ((ARRAY['ID'::character varying, 'CONTRACT'::character varying, 'CERTIFICATE'::character varying, 'PAYSLIP'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT documents_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying])::text[])))
);

CREATE TABLE salary_records (
    id            character varying(255) NOT NULL,
    basic_salary  numeric(38,2) NOT NULL,
    created_at    timestamp(6) without time zone,
    effective_date date NOT NULL,
    end_date      date,
    created_by_id character varying(255) NOT NULL,
    employee_id   character varying(255) NOT NULL
);

CREATE TABLE pay_slips (
    id               character varying(255) NOT NULL,
    basic_salary     numeric(38,2) NOT NULL,
    created_at       timestamp(6) without time zone,
    gross_salary     numeric(38,2) NOT NULL,
    medical_aid      numeric(38,2),
    month            character varying(255) NOT NULL,
    net_salary       numeric(38,2) NOT NULL,
    other_deductions numeric(38,2),
    paye             numeric(38,2) NOT NULL,
    pension_fund     numeric(38,2),
    tax_year         integer NOT NULL,
    uif              numeric(38,2) NOT NULL,
    employee_id      character varying(255) NOT NULL
);

CREATE TABLE salary_increase_requests (
    id                  character varying(255) NOT NULL,
    created_at          timestamp(6) without time zone,
    current_salary      numeric(38,2) NOT NULL,
    increase_percentage numeric(38,2) NOT NULL,
    justification       character varying(255) NOT NULL,
    proposed_salary     numeric(38,2) NOT NULL,
    rejection_reason    character varying(255),
    reviewed_at         timestamp(6) without time zone,
    status              character varying(255) NOT NULL,
    employee_id         character varying(255) NOT NULL,
    requested_by_id     character varying(255) NOT NULL,
    reviewed_by_id      character varying(255),
    CONSTRAINT salary_increase_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);

CREATE TABLE benefit_applications (
    id              character varying(255) NOT NULL,
    created_at      timestamp(6) without time zone,
    reviewed_at     timestamp(6) without time zone,
    status          character varying(255) NOT NULL,
    benefit_type_id bigint NOT NULL,
    employee_id     character varying(255) NOT NULL,
    reviewed_by_id  character varying(255),
    CONSTRAINT benefit_applications_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);

CREATE TABLE employee_benefits (
    id              character varying(255) NOT NULL,
    end_date        date,
    start_date      date NOT NULL,
    status          character varying(255) NOT NULL,
    benefit_type_id bigint NOT NULL,
    employee_id     character varying(255) NOT NULL,
    CONSTRAINT employee_benefits_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);

CREATE TABLE performance_cycles (
    id         character varying(255) NOT NULL,
    end_date   date NOT NULL,
    name       character varying(255) NOT NULL,
    start_date date NOT NULL,
    status     character varying(255) NOT NULL,
    CONSTRAINT performance_cycles_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'CLOSED'::character varying])::text[])))
);

CREATE TABLE performance_goals (
    id            character varying(255) NOT NULL,
    created_at    timestamp(6) without time zone,
    description   character varying(255),
    rating        integer,
    status        character varying(255) NOT NULL,
    target_date   date NOT NULL,
    title         character varying(255) NOT NULL,
    created_by_id character varying(255) NOT NULL,
    cycle_id      character varying(255) NOT NULL,
    employee_id   character varying(255) NOT NULL,
    CONSTRAINT performance_goals_status_check CHECK (((status)::text = ANY ((ARRAY['NOT_STARTED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);

CREATE TABLE performance_reviews (
    id                    character varying(255) NOT NULL,
    acknowledged_at       timestamp(6) without time zone,
    areas_for_improvement character varying(255),
    comments              character varying(255),
    created_at            timestamp(6) without time zone,
    overall_rating        integer NOT NULL,
    status                character varying(255) NOT NULL,
    strengths             character varying(255),
    cycle_id              character varying(255) NOT NULL,
    employee_id           character varying(255) NOT NULL,
    reviewer_id           character varying(255) NOT NULL,
    CONSTRAINT performance_reviews_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'SUBMITTED'::character varying, 'ACKNOWLEDGED'::character varying])::text[])))
);

CREATE TABLE notifications (
    id                  character varying(255) NOT NULL,
    created_at          timestamp(6) without time zone,
    is_read             boolean NOT NULL,
    message             character varying(255) NOT NULL,
    related_entity_id   character varying(255),
    related_entity_type character varying(255),
    title               character varying(255) NOT NULL,
    type                character varying(255) NOT NULL,
    recipient_id        character varying(255) NOT NULL,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['LEAVE'::character varying, 'TIMESHEET'::character varying, 'SALARY'::character varying, 'DOCUMENT'::character varying, 'GENERAL'::character varying])::text[])))
);

CREATE TABLE audit_logs (
    id              character varying(255) NOT NULL,
    action          character varying(255) NOT NULL,
    entity_id       character varying(255),
    entity_type     character varying(255) NOT NULL,
    ip_address      character varying(255),
    new_value       text,
    old_value       text,
    "timestamp"     timestamp(6) without time zone NOT NULL,
    performed_by_id character varying(255)
);

CREATE TABLE password_reset_tokens (
    id          character varying(255) NOT NULL,
    created_at  timestamp(6) without time zone,
    expires_at  timestamp(6) without time zone NOT NULL,
    token       character varying(255) NOT NULL,
    used_at     timestamp(6) without time zone,
    employee_id character varying(255) NOT NULL
);

CREATE TABLE refresh_tokens (
    id          character varying(255) NOT NULL,
    created_at  timestamp(6) without time zone,
    expires_at  timestamp(6) without time zone NOT NULL,
    revoked     boolean NOT NULL,
    token_hash  character varying(255) NOT NULL,
    employee_id character varying(255) NOT NULL
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Primary keys
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE ONLY departments              ADD CONSTRAINT departments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY teams                    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);
ALTER TABLE ONLY leave_types              ADD CONSTRAINT leave_types_pkey PRIMARY KEY (id);
ALTER TABLE ONLY benefit_types            ADD CONSTRAINT benefit_types_pkey PRIMARY KEY (id);
ALTER TABLE ONLY tax_brackets             ADD CONSTRAINT tax_brackets_pkey PRIMARY KEY (id);
ALTER TABLE ONLY employees                ADD CONSTRAINT employees_pkey PRIMARY KEY (id);
ALTER TABLE ONLY leave_balances           ADD CONSTRAINT leave_balances_pkey PRIMARY KEY (id);
ALTER TABLE ONLY leave_requests           ADD CONSTRAINT leave_requests_pkey PRIMARY KEY (id);
ALTER TABLE ONLY timesheets               ADD CONSTRAINT timesheets_pkey PRIMARY KEY (id);
ALTER TABLE ONLY timesheet_entries        ADD CONSTRAINT timesheet_entries_pkey PRIMARY KEY (id);
ALTER TABLE ONLY documents                ADD CONSTRAINT documents_pkey PRIMARY KEY (id);
ALTER TABLE ONLY salary_records           ADD CONSTRAINT salary_records_pkey PRIMARY KEY (id);
ALTER TABLE ONLY pay_slips                ADD CONSTRAINT pay_slips_pkey PRIMARY KEY (id);
ALTER TABLE ONLY salary_increase_requests ADD CONSTRAINT salary_increase_requests_pkey PRIMARY KEY (id);
ALTER TABLE ONLY benefit_applications     ADD CONSTRAINT benefit_applications_pkey PRIMARY KEY (id);
ALTER TABLE ONLY employee_benefits        ADD CONSTRAINT employee_benefits_pkey PRIMARY KEY (id);
ALTER TABLE ONLY performance_cycles       ADD CONSTRAINT performance_cycles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY performance_goals        ADD CONSTRAINT performance_goals_pkey PRIMARY KEY (id);
ALTER TABLE ONLY performance_reviews      ADD CONSTRAINT performance_reviews_pkey PRIMARY KEY (id);
ALTER TABLE ONLY notifications            ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE ONLY audit_logs               ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY password_reset_tokens    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY refresh_tokens           ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);

-- ─────────────────────────────────────────────────────────────────────────────
-- Unique constraints (Hibernate-generated names)
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE ONLY benefit_types         ADD CONSTRAINT uk2rjsrsvp8neqcc7k6rceosc2u UNIQUE (name);
ALTER TABLE ONLY password_reset_tokens ADD CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token);
ALTER TABLE ONLY employees             ADD CONSTRAINT uk9aw59jtyajbpyr0q02h20ahql UNIQUE (employee_number);
ALTER TABLE ONLY departments           ADD CONSTRAINT ukj6cwks7xecs5jov19ro8ge3qk UNIQUE (name);
ALTER TABLE ONLY employees             ADD CONSTRAINT ukj9xgmd0ya5jmus09o0b8pqrpb UNIQUE (email);
ALTER TABLE ONLY leave_types           ADD CONSTRAINT ukjk0ragqnw78kwwdopm49iea60 UNIQUE (name);
ALTER TABLE ONLY refresh_tokens        ADD CONSTRAINT uko2mlirhldriil2y7krapq4frt UNIQUE (token_hash);

-- ─────────────────────────────────────────────────────────────────────────────
-- Foreign keys (Hibernate-generated names)
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE ONLY teams                    ADD CONSTRAINT fkkteyamwleykiqb2nv0cu2fc3r FOREIGN KEY (department_id) REFERENCES departments(id);
ALTER TABLE ONLY employees                ADD CONSTRAINT fkgy4qe3dnqrm3ktd76sxp7n4c2 FOREIGN KEY (department_id) REFERENCES departments(id);
ALTER TABLE ONLY employees                ADD CONSTRAINT fka5cxjw6yuqlbp0np1g51o03gf FOREIGN KEY (team_id) REFERENCES teams(id);
ALTER TABLE ONLY employees                ADD CONSTRAINT fki4365uo9af35g7jtbc2rteukt FOREIGN KEY (manager_id) REFERENCES employees(id);
ALTER TABLE ONLY leave_balances           ADD CONSTRAINT fkmvepkwsegu6bt3ps5rfh1dx92 FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE ONLY leave_balances           ADD CONSTRAINT fk86791wotycqa54js45s9396wy FOREIGN KEY (leave_type_id) REFERENCES leave_types(id);
ALTER TABLE ONLY leave_requests           ADD CONSTRAINT fkrxff2xg1kffbjfh5maxwoqyhw FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE ONLY leave_requests           ADD CONSTRAINT fk26il0qrl79p6etqwn0ae6l43b FOREIGN KEY (leave_type_id) REFERENCES leave_types(id);
ALTER TABLE ONLY leave_requests           ADD CONSTRAINT fktcrjrh1gt06xk99n2sx4ur0o9 FOREIGN KEY (approved_by_id) REFERENCES employees(id);
ALTER TABLE ONLY timesheets               ADD CONSTRAINT fk2hwwbmujjb8y8qqkrxx9yog38 FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE ONLY timesheets               ADD CONSTRAINT fkqft0nmtud2bbryyafn8khvng4 FOREIGN KEY (approved_by_id) REFERENCES employees(id);
ALTER TABLE ONLY timesheet_entries        ADD CONSTRAINT fkpg9lqdjkngi7yvbx3s287nl6k FOREIGN KEY (timesheet_id) REFERENCES timesheets(id);
ALTER TABLE ONLY documents                ADD CONSTRAINT fkl8t4kh93dtp8uak3pvg5cqgr7 FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE ONLY documents                ADD CONSTRAINT fk4gpfe4geymybuajs6b51ke6pr FOREIGN KEY (uploaded_by_id) REFERENCES employees(id);
ALTER TABLE ONLY documents                ADD CONSTRAINT fkm4qpt54bd3y2ojo9s1arw8pqu FOREIGN KEY (verified_by_id) REFERENCES employees(id);
ALTER TABLE ONLY salary_records           ADD CONSTRAINT fkdglsilrqla44otqyp86elb7el FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE ONLY salary_records           ADD CONSTRAINT fksbt2dfv5uv9grwuickhgmxjjd FOREIGN KEY (created_by_id) REFERENCES employees(id);
ALTER TABLE ONLY pay_slips                ADD CONSTRAINT fk848cynw7kfip5vesmk4vfg6wh FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE ONLY salary_increase_requests ADD CONSTRAINT fko4phatk31746j4y5689mp91j1 FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE ONLY salary_increase_requests ADD CONSTRAINT fkp8cqlk8ncevrou0sub2ie0t6p FOREIGN KEY (requested_by_id) REFERENCES employees(id);
ALTER TABLE ONLY salary_increase_requests ADD CONSTRAINT fkmr432ag5v4pvnrw3ubthonn2m FOREIGN KEY (reviewed_by_id) REFERENCES employees(id);
ALTER TABLE ONLY benefit_applications     ADD CONSTRAINT fk6yxj0193ysose1rpenyotqhol FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE ONLY benefit_applications     ADD CONSTRAINT fka7yse4b0vqrukmr2febwi74wy FOREIGN KEY (benefit_type_id) REFERENCES benefit_types(id);
ALTER TABLE ONLY benefit_applications     ADD CONSTRAINT fk659w4f2t73lflvlrhph536xqy FOREIGN KEY (reviewed_by_id) REFERENCES employees(id);
ALTER TABLE ONLY employee_benefits        ADD CONSTRAINT fk2o4pgfj3ohbhrg6h8oubfmxpg FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE ONLY employee_benefits        ADD CONSTRAINT fkhmlyvolnrhwi00lq8egbxt5vl FOREIGN KEY (benefit_type_id) REFERENCES benefit_types(id);
ALTER TABLE ONLY performance_goals        ADD CONSTRAINT fk7jmeunxtph8ljykxd2kyc3ay3 FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE ONLY performance_goals        ADD CONSTRAINT fk495g53c6gltpm9bis8v420opk FOREIGN KEY (created_by_id) REFERENCES employees(id);
ALTER TABLE ONLY performance_goals        ADD CONSTRAINT fkpgqjotj8qn0gqo9k0gb5miyst FOREIGN KEY (cycle_id) REFERENCES performance_cycles(id);
ALTER TABLE ONLY performance_reviews      ADD CONSTRAINT fk75f19q3rvitsw5bl5o3k0lirt FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE ONLY performance_reviews      ADD CONSTRAINT fk57bxpu5rccy6vvcqolbnbqal0 FOREIGN KEY (reviewer_id) REFERENCES employees(id);
ALTER TABLE ONLY performance_reviews      ADD CONSTRAINT fkop96af0yq74cc2knxcrextcc4 FOREIGN KEY (cycle_id) REFERENCES performance_cycles(id);
ALTER TABLE ONLY notifications            ADD CONSTRAINT fkfrgm3uwh6p32y1fucs5jl18uc FOREIGN KEY (recipient_id) REFERENCES employees(id);
ALTER TABLE ONLY audit_logs               ADD CONSTRAINT fkqgbyue4jtvwdodculq927cqys FOREIGN KEY (performed_by_id) REFERENCES employees(id);
ALTER TABLE ONLY password_reset_tokens    ADD CONSTRAINT fksw5coj33ux4dbhs9ollqlccfl FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE ONLY refresh_tokens           ADD CONSTRAINT fkbc2g03lqwwiubc3wfmspa9eg6 FOREIGN KEY (employee_id) REFERENCES employees(id);
